/*
 * Copyright (C) 2010-2016 Christian Gleissner
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.github.jdot.mapper;

import com.github.jdot.file.builder.DomainMapperBuilder;

// TODO Merge with TypeMapper. There is no reason to have two mappers and they both need to be
// used during code generation of the mappers, i.e. usage of not yet created mappers when creating
// mappers.

/**
 * Mapper for domain and view classes. Implementations of this interface are generated by {@link DomainMapperBuilder}.
 * 
 * @author Christian Gleissner
 * @param <DOMAIN>
 * @param <VIEW>
 */
public interface DomainMapper<DOMAIN, VIEW> {

    DOMAIN toDomain(VIEW view);

    VIEW toView(DOMAIN domain);

}
